# Generated by Django 5.2.17 on 2026-08-07 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("is_borderline", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("green", "green"),
                            ("yellow", "yellow"),
                            ("red", "red"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_text", models.TextField()),
                ("input_kind", models.CharField(max_length=8)),
                (
                    "resolved_domain",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("owned_profile_urls", models.JSONField(default=list)),
                ("owned_social_handles", models.JSONField(default=list)),
                ("selected_categories", models.JSONField(default=list)),
                ("borderline_options", models.JSONField(default=dict)),
                ("lookback_months", models.IntegerField(default=36)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("blue", "blue"),
                            ("green", "green"),
                            ("yellow", "yellow"),
                            ("red", "red"),
                        ],
                        default="blue",
                        max_length=8,
                    ),
                ),
                ("generation", models.IntegerField(default=1)),
                ("celery_task_ids", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("executive_overview", models.TextField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("warnings", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("url", models.TextField()),
                ("canonical_url", models.TextField()),
                ("source", models.CharField(max_length=255)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("snippet", models.TextField(default="")),
                ("display_order", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="research.category",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.AddField(
            model_name="category",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="research.run",
            ),
        ),
    ]
