# Generated by Django 5.2.17 on 2026-08-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="sentiment_label",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="sentiment_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
