# Generated by Django 5.2.17 on 2026-08-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_contentitem_sentiment_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="sentiment_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
